import { setDefaultOptions } from "date-fns";
import { ptBR } from "date-fns/locale";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "./_lib/utils";

import "./globals.css";
import { Footer } from "./_components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

setDefaultOptions({
  locale: ptBR
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("dark flex flex-col relative min-h-screen", inter.className)}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
